//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsmsDatabaseFolders.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SsmsDatabaseFolders.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Readonly ähnelt.
        /// </summary>
        internal static string FolderNameReadonly {
            get {
                return ResourceManager.GetString("FolderNameReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database Folder Display Options ähnelt.
        /// </summary>
        internal static string PropertyCategoryDatabaseFolderOptionsDatabaseFolderDisplayOptions {
            get {
                return ResourceManager.GetString("PropertyCategoryDatabaseFolderOptionsDatabaseFolderDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activates grouping of databases in folders by using that part of the database names before the first underscore ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsGroupDatabasesByName {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsGroupDatabasesByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use a list of regular expressions to build the names of the folders from the name of the database (f.e. &quot;^(AppFabric)&quot; groups all databases in a folder called AppFabric if they start with the same string) ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsRegularExpressions {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use a separate folder for readonly databases ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsSeparateReadonlyDatabases {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsSeparateReadonlyDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group databases in folders by name ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsGroupDatabasesByName {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsGroupDatabasesByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build folder name by regular expressions ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsRegularExpressions {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separate folders for readonly databases ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsSeparateReadonlyDatabases {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsSeparateReadonlyDatabases", resourceCulture);
            }
        }
    }
}
