//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsmsDatabaseFolders.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SsmsDatabaseFolders.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;choose a folder name&gt; ähnelt.
        /// </summary>
        internal static string DefaultCustomFolderName {
            get {
                return ResourceManager.GetString("DefaultCustomFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Readonly ähnelt.
        /// </summary>
        internal static string FolderNameReadonly {
            get {
                return ResourceManager.GetString("FolderNameReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        internal static string PropertyCategoryDatabaseFolderOptionsActive {
            get {
                return ResourceManager.GetString("PropertyCategoryDatabaseFolderOptionsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database Folder Display Options ähnelt.
        /// </summary>
        internal static string PropertyCategoryDatabaseFolderOptionsDatabaseFolderDisplayOptions {
            get {
                return ResourceManager.GetString("PropertyCategoryDatabaseFolderOptionsDatabaseFolderDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sets the background color ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationBackColor {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sets the name of the custom folder ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationCustomFolderName {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationCustomFolderName" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use a list of regular expressions to group databases within the custom folder (f.e. &quot;^(AppFabric)&quot; groups all databases within the custom folder if they start with the same string) ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationRegularExpressions {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationRegularExpressio" +
                        "ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sets a list of configurations for custom folders ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurations {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if set to true the databases inside the custom folder will be grouped by the other mechanism, too ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationUseOtherGroupingMethodsInside {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsCustomFolderConfigurationUseOtherGrouping" +
                        "MethodsInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group databases within the Object Explorer into folders. ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsEnabled {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show separate debug output pane ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsEnableDebugOutput {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsEnableDebugOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activates grouping of databases in folders by using that part of the database names before the first underscore ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsGroupDatabasesByName {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsGroupDatabasesByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use a list of regular expressions to build the names of the folders from the name of the database (f.e. &quot;^(AppFabric)&quot; groups all databases in a folder called AppFabric if they start with the same string) ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsRegularExpressions {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use a separate folder for readonly databases ähnelt.
        /// </summary>
        internal static string PropertyDescriptionDatabaseFolderOptionsSeparateReadonlyDatabases {
            get {
                return ResourceManager.GetString("PropertyDescriptionDatabaseFolderOptionsSeparateReadonlyDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backcolor ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationBackColor {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom folder name ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationCustomFolderName {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationCustomFolderName" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort databases in folder by regular expressions ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationRegularExpressions {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationRegularExpressio" +
                        "ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom folder configurations ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurations {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use other grouping mechanisms inside the custom folder ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationUseOtherGroupingMethodsInside {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsCustomFolderConfigurationUseOtherGrouping" +
                        "MethodsInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsEnabled {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show separate debug output pane ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsEnableDebugOutput {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsEnableDebugOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group databases in folders by name ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsGroupDatabasesByName {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsGroupDatabasesByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build folder name by regular expressions ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsRegularExpressions {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separate folders for readonly databases ähnelt.
        /// </summary>
        internal static string PropertyDisplayNameDatabaseFolderOptionsSeparateReadonlyDatabases {
            get {
                return ResourceManager.GetString("PropertyDisplayNameDatabaseFolderOptionsSeparateReadonlyDatabases", resourceCulture);
            }
        }
    }
}
